# Generated by Django 5.2.17 on 2026-08-04 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128, verbose_name='عملیات')),
                ('target', models.CharField(blank=True, max_length=255, verbose_name='هدف')),
                ('severity', models.CharField(choices=[('info', 'اطلاع'), ('warning', 'هشدار'), ('critical', 'بحرانی')], default='info', max_length=16)),
                ('message_fa', models.TextField(verbose_name='شرح رویداد')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گزارش ممیزی',
                'verbose_name_plural': 'گزارش\u200cهای ممیزی',
                'ordering': ['-created_at'],
            },
        ),
    ]
