# Generated by Django 5.2.17 on 2026-08-04 16:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=128, unique=True, verbose_name='عنوان نقش')),
                ('can_view_live', models.BooleanField(default=True, verbose_name='مشاهده پخش زنده')),
                ('can_view_playback', models.BooleanField(default=False, verbose_name='بازبینی آرشیو')),
                ('can_export_video', models.BooleanField(default=False, verbose_name='خروجی ویدئو')),
                ('can_control_ptz', models.BooleanField(default=False, verbose_name='کنترل PTZ')),
                ('can_manage_cameras', models.BooleanField(default=False, verbose_name='مدیریت دوربین\u200cها')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='مدیریت کاربران')),
                ('can_approve_critical', models.BooleanField(default=False, verbose_name='تأیید عملیات حساس (چهارچشمی)')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name_fa', models.CharField(blank=True, max_length=255, verbose_name='نام کامل (فارسی)')),
                ('is_ad_account', models.BooleanField(default=False, verbose_name='حساب اکتیو دایرکتوری')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='شماره تماس')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FourEyesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('operation', models.CharField(max_length=64, verbose_name='عملیات')),
                ('payload', models.JSONField(verbose_name='پارامترهای عملیات')),
                ('signature_a', models.TextField(blank=True)),
                ('signature_b', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('executed', 'اجرا شده')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('approver_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foureyes_a', to=settings.AUTH_USER_MODEL)),
                ('approver_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foureyes_b', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foureyes_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست احراز چهارچشمی',
                'verbose_name_plural': 'درخواست\u200cهای احراز چهارچشمی',
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_group', models.ForeignKey(blank=True, help_text='در صورت خالی بودن، نقش در کل سامانه اعمال می\u200cشود.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cameras.cameragroup')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'انتساب نقش',
                'verbose_name_plural': 'انتساب نقش\u200cها',
                'unique_together': {('user', 'role', 'camera_group')},
            },
        ),
    ]
