# Generated by Django 5.2.17 on 2026-08-04 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hostname', models.CharField(max_length=255, verbose_name='نام میزبان')),
                ('grpc_endpoint', models.CharField(max_length=255, verbose_name='آدرس gRPC')),
                ('gpu_available', models.BooleanField(default=False, verbose_name='پردازنده گرافیکی')),
                ('simd_capabilities', models.JSONField(default=list, verbose_name='قابلیت\u200cهای SIMD')),
                ('is_online', models.BooleanField(default=False, verbose_name='آنلاین')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'سرور ضبط',
                'verbose_name_plural': 'سرورهای ضبط',
            },
        ),
        migrations.CreateModel(
            name='CameraGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=255, verbose_name='نام گروه')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cameras.cameragroup')),
            ],
            options={
                'verbose_name': 'گروه دوربین',
                'verbose_name_plural': 'گروه\u200cهای دوربین',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name_fa', models.CharField(max_length=255, verbose_name='نام دوربین')),
                ('onvif_endpoint', models.CharField(max_length=512, verbose_name='آدرس ONVIF')),
                ('username', models.CharField(max_length=128)),
                ('password_encrypted', models.TextField()),
                ('rtsp_main_url', models.CharField(max_length=512, verbose_name='جریان اصلی (۴K)')),
                ('rtsp_sub_url', models.CharField(max_length=512, verbose_name='جریان فرعی (۳۶۰p)')),
                ('rtsp_mid_url', models.CharField(blank=True, max_length=512, verbose_name='جریان میانی (۷۲۰p/۱۰۸۰p)')),
                ('codec', models.CharField(choices=[('h264', 'H.264'), ('h265', 'H.265')], default='h265', max_length=8)),
                ('recording_enabled', models.BooleanField(default=True, verbose_name='ضبط فعال')),
                ('retention_days', models.PositiveIntegerField(default=30, verbose_name='مدت نگهداری (روز)')),
                ('onvif_motion_events', models.BooleanField(default=False, verbose_name='رویداد حرکتی ONVIF (لایه ۱)')),
                ('edge_storage_profile_g', models.BooleanField(default=False, verbose_name='ذخیره\u200cسازی لبه (ONVIF Profile G)')),
                ('map_latitude', models.FloatField(blank=True, null=True)),
                ('map_longitude', models.FloatField(blank=True, null=True)),
                ('fov_direction_deg', models.FloatField(blank=True, null=True, verbose_name='جهت دید (درجه)')),
                ('fov_angle_deg', models.FloatField(blank=True, null=True, verbose_name='زاویه دید (درجه)')),
                ('config_revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='cameras.cameragroup')),
                ('recording_server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='cameras.recordingserver')),
            ],
            options={
                'verbose_name': 'دوربین',
                'verbose_name_plural': 'دوربین\u200cها',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MotionRoiGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_cols', models.PositiveSmallIntegerField(default=32)),
                ('grid_rows', models.PositiveSmallIntegerField(default=24)),
                ('bitmask', models.BinaryField()),
                ('sensitivity', models.PositiveSmallIntegerField(default=50, verbose_name='حساسیت')),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roi', to='cameras.camera')),
            ],
            options={
                'verbose_name': 'شبکه ناحیه حساس حرکت',
                'verbose_name_plural': 'شبکه\u200cهای ناحیه حساس حرکت',
            },
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['group', 'recording_enabled'], name='camera_group_rec_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['codec'], name='camera_codec_idx'),
        ),
    ]
