# Generated by Django 5.2.13 on 2026-08-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='brand',
            field=models.CharField(choices=[('hikvision', 'هیک\u200cویژن (Hikvision)'), ('dahua', 'داهوا (Dahua)'), ('uniview', 'یونی\u200cویو (Uniview)'), ('axis', 'اکسیس (Axis)'), ('generic-onvif', 'استاندارد (ONVIF)'), ('custom', 'سفارشی (ورود دستی URL)')], default='generic-onvif', max_length=32, verbose_name='مدل / برند'),
        ),
        migrations.AddField(
            model_name='camera',
            name='ip_address',
            field=models.CharField(blank=True, max_length=64, verbose_name='آدرس IP'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='onvif_endpoint',
            field=models.CharField(blank=True, help_text='در صورت خالی بودن، به صورت خودکار ساخته می\u200cشود.', max_length=512, verbose_name='آدرس سرویس ONVIF'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='password_encrypted',
            field=models.TextField(verbose_name='رمز عبور دوربین'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_main_url',
            field=models.CharField(blank=True, help_text='به صورت خودکار پر می\u200cشود — به سلیقه می\u200cتوانید دستی تغییر دهید.', max_length=512, verbose_name='جریان اصلی (۴K)'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_mid_url',
            field=models.CharField(blank=True, help_text='اختیاری — برای شبکه\u200cهای ۴ دوربینه استفاده می\u200cشود.', max_length=512, verbose_name='جریان میانی (۷۲۰p/۱۰۸۰p)'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_sub_url',
            field=models.CharField(blank=True, help_text='به صورت خودکار پر می\u200cشود — به سلیقه می\u200cتوانید دستی تغییر دهید.', max_length=512, verbose_name='جریان فرعی (۳۶۰p)'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='username',
            field=models.CharField(max_length=128, verbose_name='نام کاربری دوربین'),
        ),
    ]
