# Generated by Django 5.2.13 on 2026-08-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_brand_camera_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='brand',
            field=models.CharField(choices=[('hikvision', 'هیک\u200cویژن (Hikvision)'), ('dahua', 'داهوا (Dahua)'), ('uniview', 'یونی\u200cویو (Uniview)'), ('axis', 'اکسیس (Axis)'), ('aria', 'آریا (Aria)'), ('cambiz', 'کامبیز (Cambiz)'), ('atal', 'آتال (Atal)'), ('radin', 'رادین (Radin)'), ('parsan', 'پارسان (Parsan)'), ('pejvak', 'پژواک (Pejvak)'), ('sana', 'سانا (Sana)'), ('arman', 'آرمان (Arman)'), ('mersad', 'مرصاد (Mersad)'), ('generic-onvif', 'استاندارد (ONVIF)'), ('custom', 'سفارشی (ورود دستی URL)')], default='generic-onvif', help_text='برند دوربین را انتخاب کنید. برای دوربین\u200cهای ایرانی و استاندارد ONVIF، تنظیمات به صورت خودکار از خود دوربین تشخیص داده می\u200cشود.', max_length=32, verbose_name='مدل / برند'),
        ),
    ]
