# Generated by Django 5.2.13 on 2026-08-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_alter_camera_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingserver',
            name='storage_path',
            field=models.CharField(default='/mnt/vms-archive', help_text='پوشه\u200cای که ضبط\u200cها در این سرور در آن نوشته می\u200cشوند (مثلاً /mnt/vms-archive). باید روی همان سرور وجود داشته باشد و قابل نوشتن باشد.', max_length=512, verbose_name='مسیر ذخیره\u200cسازی'),
        ),
        migrations.AlterField(
            model_name='recordingserver',
            name='gpu_available',
            field=models.BooleanField(default=False, help_text='به صورت خودکار هنگام روشن شدن سرور تشخیص داده می\u200cشود.', verbose_name='پردازنده گرافیکی'),
        ),
        migrations.AlterField(
            model_name='recordingserver',
            name='grpc_endpoint',
            field=models.CharField(help_text='آدرس host:port که بقیه سامانه با این سرور ارتباط برقرار می\u200cکنند. این مقدار هنگام روشن شدن سرور به صورت خودکار ثبت می\u200cشود و نیازی به ورود دستی ندارد.', max_length=255, verbose_name='آدرس gRPC'),
        ),
        migrations.AlterField(
            model_name='recordingserver',
            name='hostname',
            field=models.CharField(help_text='نام یا آدرس شبکه\u200cای سرور، مثلاً «سرور ضبط ساختمان مرکزی» یا rec-01.', max_length=255, verbose_name='نام میزبان'),
        ),
        migrations.AlterField(
            model_name='recordingserver',
            name='is_online',
            field=models.BooleanField(default=False, help_text='آخرین وضعیت اتصال سرور؛ به صورت خودکار به\u200cروزرسانی می\u200cشود.', verbose_name='آنلاین'),
        ),
        migrations.AlterField(
            model_name='recordingserver',
            name='simd_capabilities',
            field=models.JSONField(default=list, help_text='شتاب\u200cهای پردازنده (مثل AVX2 یا AVX-512) که تشخیص حرکت را سریع\u200cتر می\u200cکنند. به صورت خودکار تشخیص داده می\u200cشود.', verbose_name='قابلیت\u200cهای SIMD'),
        ),
    ]
