# Generated by Django 5.2.17 on 2026-08-04 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=255, verbose_name='نام')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='کد ملی')),
                ('is_watchlisted', models.BooleanField(default=False, verbose_name='در فهرست مراقبت')),
                ('embedding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'هویت',
                'verbose_name_plural': 'هویت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='DetectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_timestamp', models.DateTimeField(db_index=True)),
                ('label', models.CharField(max_length=64)),
                ('attributes', models.JSONField(default=dict)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('bbox', models.JSONField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='cameras.camera')),
                ('matched_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forensic.identity')),
            ],
            options={
                'verbose_name': 'رکورد تشخیص',
                'verbose_name_plural': 'رکوردهای تشخیص',
                'indexes': [models.Index(fields=['camera', 'utc_timestamp'], name='forensic_de_camera__b05013_idx'), models.Index(fields=['label', 'utc_timestamp'], name='forensic_de_label_8db09b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SynopsisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('from_utc', models.DateTimeField(verbose_name='شروع بازه (UTC)')),
                ('to_utc', models.DateTimeField(verbose_name='پایان بازه (UTC)')),
                ('target_duration_s', models.PositiveIntegerField(default=120, verbose_name='مدت کلیپ خلاصه (ثانیه)')),
                ('state', models.CharField(choices=[('queued', 'در صف'), ('extracting', 'استخراج اشیاء متحرک'), ('compacting', 'فشرده\u200cسازی زمانی'), ('rendering', 'رندر خروجی'), ('done', 'تکمیل شد'), ('failed', 'ناموفق')], default='queued', max_length=16, verbose_name='وضعیت')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='درصد پیشرفت')),
                ('result_manifest', models.JSONField(blank=True, null=True, verbose_name='مانیفست نتیجه')),
                ('error_fa', models.CharField(blank=True, max_length=255, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synopsis_jobs', to='cameras.camera', verbose_name='دوربین')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='synopsis_jobs', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده')),
            ],
            options={
                'verbose_name': 'خلاصه\u200cسازی ویدئو',
                'verbose_name_plural': 'خلاصه\u200cسازی\u200cهای ویدئو',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['camera', 'state'], name='forensic_sy_camera__e92f7d_idx')],
            },
        ),
    ]
