# Generated by Django 5.2.17 on 2026-08-04 16:46

import apps.layouts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GridLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name_fa', models.CharField(max_length=255, verbose_name='نام چیدمان')),
                ('is_shared', models.BooleanField(default=False, verbose_name='اشتراک\u200cگذاری با سایر کاربران')),
                ('layout_json', models.JSONField(validators=[apps.layouts.models.validate_layout_json], verbose_name='ساختار چیدمان')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'چیدمان نمایش',
                'verbose_name_plural': 'چیدمان\u200cهای نمایش',
                'ordering': ['-updated_at', 'id'],
                'indexes': [models.Index(fields=['is_shared'], name='layout_shared_idx'), models.Index(fields=['owner', '-updated_at'], name='layout_owner_updated_idx')],
            },
        ),
    ]
